//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichiSistemaWeb.MichiBackend {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://michisistemaws.com/", ConfigurationName="MichiBackend.OrdenWS")]
    public interface OrdenWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/OrdenWS/listaOrdenesRequest", ReplyAction="http://michisistemaws.com/OrdenWS/listaOrdenesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MichiSistemaWeb.MichiBackend.listaOrdenesResponse listaOrdenes(MichiSistemaWeb.MichiBackend.listaOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/OrdenWS/listaOrdenesRequest", ReplyAction="http://michisistemaws.com/OrdenWS/listaOrdenesResponse")]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaOrdenesResponse> listaOrdenesAsync(MichiSistemaWeb.MichiBackend.listaOrdenesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class orden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantDiasField;
        
        private int clienteIDField;
        
        private estadoFechaDevolucion estadoField;
        
        private localDate fecha_devolucionField;
        
        private localDate fecha_emisiónField;
        
        private localDate fecha_entregaField;
        
        private localDateTime fecha_registroField;
        
        private int idOrdenField;
        
        private detalleOrden[] listaOrdenesField;
        
        private double saldoField;
        
        private string setUpPersonalizadoField;
        
        private tipoEstadoDevolucion tipoEstadoDevolucionField;
        
        private bool tipoEstadoDevolucionFieldSpecified;
        
        private tipoRecepcion tipoRecepcionField;
        
        private bool tipoRecepcionFieldSpecified;
        
        private double totalPagarField;
        
        private int trabajadorIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantDias {
            get {
                return this.cantDiasField;
            }
            set {
                this.cantDiasField = value;
                this.RaisePropertyChanged("cantDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int clienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
                this.RaisePropertyChanged("clienteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoFechaDevolucion estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDate fecha_devolucion {
            get {
                return this.fecha_devolucionField;
            }
            set {
                this.fecha_devolucionField = value;
                this.RaisePropertyChanged("fecha_devolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDate fecha_emisión {
            get {
                return this.fecha_emisiónField;
            }
            set {
                this.fecha_emisiónField = value;
                this.RaisePropertyChanged("fecha_emisión");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDate fecha_entrega {
            get {
                return this.fecha_entregaField;
            }
            set {
                this.fecha_entregaField = value;
                this.RaisePropertyChanged("fecha_entrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public localDateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                this.fecha_registroField = value;
                this.RaisePropertyChanged("fecha_registro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idOrden {
            get {
                return this.idOrdenField;
            }
            set {
                this.idOrdenField = value;
                this.RaisePropertyChanged("idOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaOrdenes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public detalleOrden[] listaOrdenes {
            get {
                return this.listaOrdenesField;
            }
            set {
                this.listaOrdenesField = value;
                this.RaisePropertyChanged("listaOrdenes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("saldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string setUpPersonalizado {
            get {
                return this.setUpPersonalizadoField;
            }
            set {
                this.setUpPersonalizadoField = value;
                this.RaisePropertyChanged("setUpPersonalizado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public tipoEstadoDevolucion tipoEstadoDevolucion {
            get {
                return this.tipoEstadoDevolucionField;
            }
            set {
                this.tipoEstadoDevolucionField = value;
                this.RaisePropertyChanged("tipoEstadoDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoEstadoDevolucionSpecified {
            get {
                return this.tipoEstadoDevolucionFieldSpecified;
            }
            set {
                this.tipoEstadoDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("tipoEstadoDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public tipoRecepcion tipoRecepcion {
            get {
                return this.tipoRecepcionField;
            }
            set {
                this.tipoRecepcionField = value;
                this.RaisePropertyChanged("tipoRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoRecepcionSpecified {
            get {
                return this.tipoRecepcionFieldSpecified;
            }
            set {
                this.tipoRecepcionFieldSpecified = value;
                this.RaisePropertyChanged("tipoRecepcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public double totalPagar {
            get {
                return this.totalPagarField;
            }
            set {
                this.totalPagarField = value;
                this.RaisePropertyChanged("totalPagar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int trabajadorID {
            get {
                return this.trabajadorIDField;
            }
            set {
                this.trabajadorIDField = value;
                this.RaisePropertyChanged("trabajadorID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class estadoFechaDevolucion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double penalidadField;
        
        private int tipoEstadoFechaDevol_idField;
        
        private tipoFechaDevolucion tipoFechaDevolucionField;
        
        private bool tipoFechaDevolucionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double penalidad {
            get {
                return this.penalidadField;
            }
            set {
                this.penalidadField = value;
                this.RaisePropertyChanged("penalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int tipoEstadoFechaDevol_id {
            get {
                return this.tipoEstadoFechaDevol_idField;
            }
            set {
                this.tipoEstadoFechaDevol_idField = value;
                this.RaisePropertyChanged("tipoEstadoFechaDevol_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoFechaDevolucion tipoFechaDevolucion {
            get {
                return this.tipoFechaDevolucionField;
            }
            set {
                this.tipoFechaDevolucionField = value;
                this.RaisePropertyChanged("tipoFechaDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoFechaDevolucionSpecified {
            get {
                return this.tipoFechaDevolucionFieldSpecified;
            }
            set {
                this.tipoFechaDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("tipoFechaDevolucionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoFechaDevolucion {
        
        /// <remarks/>
        DEVUELTO_POSTERIOR_A_LA_FECHA,
        
        /// <remarks/>
        DEVUELTO_ANTERIOR_A_LA_FECHA,
        
        /// <remarks/>
        DEVUELTO_FECHA_LIMITE,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private int celularField;
        
        private string emailField;
        
        private bool estadoField;
        
        private string nombresField;
        
        private int persona_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int persona_id {
            get {
                return this.persona_idField;
            }
            set {
                this.persona_idField = value;
                this.RaisePropertyChanged("persona_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class cliente : persona {
        
        private string numeroTipoClienteField;
        
        private int puntuacionField;
        
        private tipoCliente tipoClienteField;
        
        private bool tipoClienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroTipoCliente {
            get {
                return this.numeroTipoClienteField;
            }
            set {
                this.numeroTipoClienteField = value;
                this.RaisePropertyChanged("numeroTipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int puntuacion {
            get {
                return this.puntuacionField;
            }
            set {
                this.puntuacionField = value;
                this.RaisePropertyChanged("puntuacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoCliente tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoClienteSpecified {
            get {
                return this.tipoClienteFieldSpecified;
            }
            set {
                this.tipoClienteFieldSpecified = value;
                this.RaisePropertyChanged("tipoClienteSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoCliente {
        
        /// <remarks/>
        EIN,
        
        /// <remarks/>
        TIN,
        
        /// <remarks/>
        SSN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class detalleOrden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadEntregadaField;
        
        private int cantidadSolicitadaField;
        
        private int orden_idField;
        
        private double precioAsignadoField;
        
        private int productoField;
        
        private double subtotalField;
        
        private unidadMedida unidadMedidaField;
        
        private bool unidadMedidaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadEntregada {
            get {
                return this.cantidadEntregadaField;
            }
            set {
                this.cantidadEntregadaField = value;
                this.RaisePropertyChanged("cantidadEntregada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadSolicitada {
            get {
                return this.cantidadSolicitadaField;
            }
            set {
                this.cantidadSolicitadaField = value;
                this.RaisePropertyChanged("cantidadSolicitada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int orden_id {
            get {
                return this.orden_idField;
            }
            set {
                this.orden_idField = value;
                this.RaisePropertyChanged("orden_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precioAsignado {
            get {
                return this.precioAsignadoField;
            }
            set {
                this.precioAsignadoField = value;
                this.RaisePropertyChanged("precioAsignado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public unidadMedida unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unidadMedidaSpecified {
            get {
                return this.unidadMedidaFieldSpecified;
            }
            set {
                this.unidadMedidaFieldSpecified = value;
                this.RaisePropertyChanged("unidadMedidaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum unidadMedida {
        
        /// <remarks/>
        PULGADA,
        
        /// <remarks/>
        PIE,
        
        /// <remarks/>
        YARDA,
        
        /// <remarks/>
        ONZA,
        
        /// <remarks/>
        LIBRA,
        
        /// <remarks/>
        TONELADA_CORTA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoEstadoDevolucion {
        
        /// <remarks/>
        DEVUELTO_EN_BUENAS_CONDICIONES,
        
        /// <remarks/>
        DEVUELTO_EN_MALAS_CONDICIONES,
        
        /// <remarks/>
        DEVUELTO_EN_CONDICIONES_REGULARES,
        
        /// <remarks/>
        DEVUELTO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoRecepcion {
        
        /// <remarks/>
        DELIVERY,
        
        /// <remarks/>
        RECOJO_EN_TIENDA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaOrdenes", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listaOrdenesRequest {
        
        public listaOrdenesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaOrdenesResponse", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listaOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://michisistemaws.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MichiSistemaWeb.MichiBackend.orden[] @return;
        
        public listaOrdenesResponse() {
        }
        
        public listaOrdenesResponse(MichiSistemaWeb.MichiBackend.orden[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenWSChannel : MichiSistemaWeb.MichiBackend.OrdenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenWSClient : System.ServiceModel.ClientBase<MichiSistemaWeb.MichiBackend.OrdenWS>, MichiSistemaWeb.MichiBackend.OrdenWS {
        
        public OrdenWSClient() {
        }
        
        public OrdenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MichiSistemaWeb.MichiBackend.listaOrdenesResponse MichiSistemaWeb.MichiBackend.OrdenWS.listaOrdenes(MichiSistemaWeb.MichiBackend.listaOrdenesRequest request) {
            return base.Channel.listaOrdenes(request);
        }
        
        public MichiSistemaWeb.MichiBackend.orden[] listaOrdenes() {
            MichiSistemaWeb.MichiBackend.listaOrdenesRequest inValue = new MichiSistemaWeb.MichiBackend.listaOrdenesRequest();
            MichiSistemaWeb.MichiBackend.listaOrdenesResponse retVal = ((MichiSistemaWeb.MichiBackend.OrdenWS)(this)).listaOrdenes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaOrdenesResponse> MichiSistemaWeb.MichiBackend.OrdenWS.listaOrdenesAsync(MichiSistemaWeb.MichiBackend.listaOrdenesRequest request) {
            return base.Channel.listaOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaOrdenesResponse> listaOrdenesAsync() {
            MichiSistemaWeb.MichiBackend.listaOrdenesRequest inValue = new MichiSistemaWeb.MichiBackend.listaOrdenesRequest();
            return ((MichiSistemaWeb.MichiBackend.OrdenWS)(this)).listaOrdenesAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://michisistemaws.com/", ConfigurationName="MichiBackend.ClienteWS")]
    public interface ClienteWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/ClienteWS/listaClientesRequest", ReplyAction="http://michisistemaws.com/ClienteWS/listaClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MichiSistemaWeb.MichiBackend.listaClientesResponse listaClientes(MichiSistemaWeb.MichiBackend.listaClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/ClienteWS/listaClientesRequest", ReplyAction="http://michisistemaws.com/ClienteWS/listaClientesResponse")]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaClientesResponse> listaClientesAsync(MichiSistemaWeb.MichiBackend.listaClientesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaClientes", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listaClientesRequest {
        
        public listaClientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaClientesResponse", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listaClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://michisistemaws.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MichiSistemaWeb.MichiBackend.cliente[] @return;
        
        public listaClientesResponse() {
        }
        
        public listaClientesResponse(MichiSistemaWeb.MichiBackend.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteWSChannel : MichiSistemaWeb.MichiBackend.ClienteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteWSClient : System.ServiceModel.ClientBase<MichiSistemaWeb.MichiBackend.ClienteWS>, MichiSistemaWeb.MichiBackend.ClienteWS {
        
        public ClienteWSClient() {
        }
        
        public ClienteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MichiSistemaWeb.MichiBackend.listaClientesResponse MichiSistemaWeb.MichiBackend.ClienteWS.listaClientes(MichiSistemaWeb.MichiBackend.listaClientesRequest request) {
            return base.Channel.listaClientes(request);
        }
        
        public MichiSistemaWeb.MichiBackend.cliente[] listaClientes() {
            MichiSistemaWeb.MichiBackend.listaClientesRequest inValue = new MichiSistemaWeb.MichiBackend.listaClientesRequest();
            MichiSistemaWeb.MichiBackend.listaClientesResponse retVal = ((MichiSistemaWeb.MichiBackend.ClienteWS)(this)).listaClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaClientesResponse> MichiSistemaWeb.MichiBackend.ClienteWS.listaClientesAsync(MichiSistemaWeb.MichiBackend.listaClientesRequest request) {
            return base.Channel.listaClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaClientesResponse> listaClientesAsync() {
            MichiSistemaWeb.MichiBackend.listaClientesRequest inValue = new MichiSistemaWeb.MichiBackend.listaClientesRequest();
            return ((MichiSistemaWeb.MichiBackend.ClienteWS)(this)).listaClientesAsync(inValue);
        }
    }
}
