//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichiSistemaWeb.MichiBackend {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://michisistemaws.com/", ConfigurationName="MichiBackend.OrdenWS")]
    public interface OrdenWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/OrdenWS/listaOrdenesRequest", ReplyAction="http://michisistemaws.com/OrdenWS/listaOrdenesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MichiSistemaWeb.MichiBackend.listaOrdenesResponse listaOrdenes(MichiSistemaWeb.MichiBackend.listaOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/OrdenWS/listaOrdenesRequest", ReplyAction="http://michisistemaws.com/OrdenWS/listaOrdenesResponse")]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaOrdenesResponse> listaOrdenesAsync(MichiSistemaWeb.MichiBackend.listaOrdenesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class orden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantDiasField;
        
        private int clienteIDField;
        
        private estadoFechaDevolucion estadoField;
        
        private localDate fecha_devolucionField;
        
        private localDate fecha_emisiónField;
        
        private localDate fecha_entregaField;
        
        private localDateTime fecha_registroField;
        
        private int idOrdenField;
        
        private detalleOrden[] listaOrdenesField;
        
        private double saldoField;
        
        private string setUpPersonalizadoField;
        
        private tipoEstadoDevolucion tipoEstadoDevolucionField;
        
        private bool tipoEstadoDevolucionFieldSpecified;
        
        private tipoRecepcion tipoRecepcionField;
        
        private bool tipoRecepcionFieldSpecified;
        
        private double totalPagarField;
        
        private int trabajadorIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantDias {
            get {
                return this.cantDiasField;
            }
            set {
                this.cantDiasField = value;
                this.RaisePropertyChanged("cantDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int clienteID {
            get {
                return this.clienteIDField;
            }
            set {
                this.clienteIDField = value;
                this.RaisePropertyChanged("clienteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoFechaDevolucion estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDate fecha_devolucion {
            get {
                return this.fecha_devolucionField;
            }
            set {
                this.fecha_devolucionField = value;
                this.RaisePropertyChanged("fecha_devolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDate fecha_emisión {
            get {
                return this.fecha_emisiónField;
            }
            set {
                this.fecha_emisiónField = value;
                this.RaisePropertyChanged("fecha_emisión");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDate fecha_entrega {
            get {
                return this.fecha_entregaField;
            }
            set {
                this.fecha_entregaField = value;
                this.RaisePropertyChanged("fecha_entrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public localDateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                this.fecha_registroField = value;
                this.RaisePropertyChanged("fecha_registro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idOrden {
            get {
                return this.idOrdenField;
            }
            set {
                this.idOrdenField = value;
                this.RaisePropertyChanged("idOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaOrdenes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public detalleOrden[] listaOrdenes {
            get {
                return this.listaOrdenesField;
            }
            set {
                this.listaOrdenesField = value;
                this.RaisePropertyChanged("listaOrdenes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("saldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string setUpPersonalizado {
            get {
                return this.setUpPersonalizadoField;
            }
            set {
                this.setUpPersonalizadoField = value;
                this.RaisePropertyChanged("setUpPersonalizado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public tipoEstadoDevolucion tipoEstadoDevolucion {
            get {
                return this.tipoEstadoDevolucionField;
            }
            set {
                this.tipoEstadoDevolucionField = value;
                this.RaisePropertyChanged("tipoEstadoDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoEstadoDevolucionSpecified {
            get {
                return this.tipoEstadoDevolucionFieldSpecified;
            }
            set {
                this.tipoEstadoDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("tipoEstadoDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public tipoRecepcion tipoRecepcion {
            get {
                return this.tipoRecepcionField;
            }
            set {
                this.tipoRecepcionField = value;
                this.RaisePropertyChanged("tipoRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoRecepcionSpecified {
            get {
                return this.tipoRecepcionFieldSpecified;
            }
            set {
                this.tipoRecepcionFieldSpecified = value;
                this.RaisePropertyChanged("tipoRecepcionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public double totalPagar {
            get {
                return this.totalPagarField;
            }
            set {
                this.totalPagarField = value;
                this.RaisePropertyChanged("totalPagar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int trabajadorID {
            get {
                return this.trabajadorIDField;
            }
            set {
                this.trabajadorIDField = value;
                this.RaisePropertyChanged("trabajadorID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class estadoFechaDevolucion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double penalidadField;
        
        private int tipoEstadoFechaDevol_idField;
        
        private tipoFechaDevolucion tipoFechaDevolucionField;
        
        private bool tipoFechaDevolucionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double penalidad {
            get {
                return this.penalidadField;
            }
            set {
                this.penalidadField = value;
                this.RaisePropertyChanged("penalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int tipoEstadoFechaDevol_id {
            get {
                return this.tipoEstadoFechaDevol_idField;
            }
            set {
                this.tipoEstadoFechaDevol_idField = value;
                this.RaisePropertyChanged("tipoEstadoFechaDevol_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoFechaDevolucion tipoFechaDevolucion {
            get {
                return this.tipoFechaDevolucionField;
            }
            set {
                this.tipoFechaDevolucionField = value;
                this.RaisePropertyChanged("tipoFechaDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoFechaDevolucionSpecified {
            get {
                return this.tipoFechaDevolucionFieldSpecified;
            }
            set {
                this.tipoFechaDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("tipoFechaDevolucionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoFechaDevolucion {
        
        /// <remarks/>
        DEVUELTO_POSTERIOR_A_LA_FECHA,
        
        /// <remarks/>
        DEVUELTO_ANTERIOR_A_LA_FECHA,
        
        /// <remarks/>
        DEVUELTO_FECHA_LIMITE,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(trabajador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public abstract partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidosField;
        
        private int celularField;
        
        private string emailField;
        
        private bool estadoField;
        
        private string nombresField;
        
        private int persona_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int persona_id {
            get {
                return this.persona_idField;
            }
            set {
                this.persona_idField = value;
                this.RaisePropertyChanged("persona_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class trabajador : persona {
        
        private tipoTrabajador tipoTrabajadorField;
        
        private bool tipoTrabajadorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tipoTrabajador tipoTrabajador {
            get {
                return this.tipoTrabajadorField;
            }
            set {
                this.tipoTrabajadorField = value;
                this.RaisePropertyChanged("tipoTrabajador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoTrabajadorSpecified {
            get {
                return this.tipoTrabajadorFieldSpecified;
            }
            set {
                this.tipoTrabajadorFieldSpecified = value;
                this.RaisePropertyChanged("tipoTrabajadorSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoTrabajador {
        
        /// <remarks/>
        DESPACHADOR,
        
        /// <remarks/>
        DELIVERY,
        
        /// <remarks/>
        ASISTENTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class cliente : persona {
        
        private string numeroTipoClienteField;
        
        private int puntuacionField;
        
        private tipoCliente tipoClienteField;
        
        private bool tipoClienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroTipoCliente {
            get {
                return this.numeroTipoClienteField;
            }
            set {
                this.numeroTipoClienteField = value;
                this.RaisePropertyChanged("numeroTipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int puntuacion {
            get {
                return this.puntuacionField;
            }
            set {
                this.puntuacionField = value;
                this.RaisePropertyChanged("puntuacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tipoCliente tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoClienteSpecified {
            get {
                return this.tipoClienteFieldSpecified;
            }
            set {
                this.tipoClienteFieldSpecified = value;
                this.RaisePropertyChanged("tipoClienteSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoCliente {
        
        /// <remarks/>
        EIN,
        
        /// <remarks/>
        TIN,
        
        /// <remarks/>
        SSN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class localTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoPostalField;
        
        private string descripcionField;
        
        private string direccionField;
        
        private int evento_idField;
        
        private localDate fechaFinField;
        
        private localDate fechaInicioField;
        
        private localTime horaFinField;
        
        private localTime horaInicioField;
        
        private tipoEvento tipoEventoField;
        
        private bool tipoEventoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
                this.RaisePropertyChanged("codigoPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int evento_id {
            get {
                return this.evento_idField;
            }
            set {
                this.evento_idField = value;
                this.RaisePropertyChanged("evento_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public localDate fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDate fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public localTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public localTime horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoEvento tipoEvento {
            get {
                return this.tipoEventoField;
            }
            set {
                this.tipoEventoField = value;
                this.RaisePropertyChanged("tipoEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoEventoSpecified {
            get {
                return this.tipoEventoFieldSpecified;
            }
            set {
                this.tipoEventoFieldSpecified = value;
                this.RaisePropertyChanged("tipoEventoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoEvento {
        
        /// <remarks/>
        BODA,
        
        /// <remarks/>
        CUMPLEANHOS,
        
        /// <remarks/>
        CONCIERTO,
        
        /// <remarks/>
        GRADUACION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private tipoProducto categoriaProductoField;
        
        private bool categoriaProductoFieldSpecified;
        
        private string descripcionField;
        
        private int edad_minimaField;
        
        private ushort estadoField;
        
        private string nombreField;
        
        private double precioField;
        
        private int producto_idField;
        
        private int stockActualField;
        
        private int stockMinimoField;
        
        private unidadMedida unidadMedidaField;
        
        private bool unidadMedidaFieldSpecified;
        
        private double volumenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tipoProducto categoriaProducto {
            get {
                return this.categoriaProductoField;
            }
            set {
                this.categoriaProductoField = value;
                this.RaisePropertyChanged("categoriaProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaProductoSpecified {
            get {
                return this.categoriaProductoFieldSpecified;
            }
            set {
                this.categoriaProductoFieldSpecified = value;
                this.RaisePropertyChanged("categoriaProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int edad_minima {
            get {
                return this.edad_minimaField;
            }
            set {
                this.edad_minimaField = value;
                this.RaisePropertyChanged("edad_minima");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int producto_id {
            get {
                return this.producto_idField;
            }
            set {
                this.producto_idField = value;
                this.RaisePropertyChanged("producto_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stockActual {
            get {
                return this.stockActualField;
            }
            set {
                this.stockActualField = value;
                this.RaisePropertyChanged("stockActual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public unidadMedida unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unidadMedidaSpecified {
            get {
                return this.unidadMedidaFieldSpecified;
            }
            set {
                this.unidadMedidaFieldSpecified = value;
                this.RaisePropertyChanged("unidadMedidaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
                this.RaisePropertyChanged("volumen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoProducto {
        
        /// <remarks/>
        DECORACION,
        
        /// <remarks/>
        ENVASE,
        
        /// <remarks/>
        REGALO,
        
        /// <remarks/>
        EQUIPO_AUDIOVISUAL,
        
        /// <remarks/>
        VESTIMENTA,
        
        /// <remarks/>
        INVITACION,
        
        /// <remarks/>
        MOBILIARIO,
        
        /// <remarks/>
        TECNOLOGIA,
        
        /// <remarks/>
        OTRO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum unidadMedida {
        
        /// <remarks/>
        PULGADA,
        
        /// <remarks/>
        PIE,
        
        /// <remarks/>
        YARDA,
        
        /// <remarks/>
        ONZA,
        
        /// <remarks/>
        LIBRA,
        
        /// <remarks/>
        TONELADA_CORTA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class detalleOrden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadEntregadaField;
        
        private int cantidadSolicitadaField;
        
        private int orden_idField;
        
        private double precioAsignadoField;
        
        private int productoField;
        
        private double subtotalField;
        
        private unidadMedida unidadMedidaField;
        
        private bool unidadMedidaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadEntregada {
            get {
                return this.cantidadEntregadaField;
            }
            set {
                this.cantidadEntregadaField = value;
                this.RaisePropertyChanged("cantidadEntregada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadSolicitada {
            get {
                return this.cantidadSolicitadaField;
            }
            set {
                this.cantidadSolicitadaField = value;
                this.RaisePropertyChanged("cantidadSolicitada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int orden_id {
            get {
                return this.orden_idField;
            }
            set {
                this.orden_idField = value;
                this.RaisePropertyChanged("orden_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precioAsignado {
            get {
                return this.precioAsignadoField;
            }
            set {
                this.precioAsignadoField = value;
                this.RaisePropertyChanged("precioAsignado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public unidadMedida unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unidadMedidaSpecified {
            get {
                return this.unidadMedidaFieldSpecified;
            }
            set {
                this.unidadMedidaFieldSpecified = value;
                this.RaisePropertyChanged("unidadMedidaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoEstadoDevolucion {
        
        /// <remarks/>
        DEVUELTO_EN_BUENAS_CONDICIONES,
        
        /// <remarks/>
        DEVUELTO_EN_MALAS_CONDICIONES,
        
        /// <remarks/>
        DEVUELTO_EN_CONDICIONES_REGULARES,
        
        /// <remarks/>
        DEVUELTO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://michisistemaws.com/")]
    public enum tipoRecepcion {
        
        /// <remarks/>
        DELIVERY,
        
        /// <remarks/>
        RECOJO_EN_TIENDA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaOrdenes", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listaOrdenesRequest {
        
        public listaOrdenesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaOrdenesResponse", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listaOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://michisistemaws.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MichiSistemaWeb.MichiBackend.orden[] @return;
        
        public listaOrdenesResponse() {
        }
        
        public listaOrdenesResponse(MichiSistemaWeb.MichiBackend.orden[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenWSChannel : MichiSistemaWeb.MichiBackend.OrdenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenWSClient : System.ServiceModel.ClientBase<MichiSistemaWeb.MichiBackend.OrdenWS>, MichiSistemaWeb.MichiBackend.OrdenWS {
        
        public OrdenWSClient() {
        }
        
        public OrdenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MichiSistemaWeb.MichiBackend.listaOrdenesResponse MichiSistemaWeb.MichiBackend.OrdenWS.listaOrdenes(MichiSistemaWeb.MichiBackend.listaOrdenesRequest request) {
            return base.Channel.listaOrdenes(request);
        }
        
        public MichiSistemaWeb.MichiBackend.orden[] listaOrdenes() {
            MichiSistemaWeb.MichiBackend.listaOrdenesRequest inValue = new MichiSistemaWeb.MichiBackend.listaOrdenesRequest();
            MichiSistemaWeb.MichiBackend.listaOrdenesResponse retVal = ((MichiSistemaWeb.MichiBackend.OrdenWS)(this)).listaOrdenes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaOrdenesResponse> MichiSistemaWeb.MichiBackend.OrdenWS.listaOrdenesAsync(MichiSistemaWeb.MichiBackend.listaOrdenesRequest request) {
            return base.Channel.listaOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaOrdenesResponse> listaOrdenesAsync() {
            MichiSistemaWeb.MichiBackend.listaOrdenesRequest inValue = new MichiSistemaWeb.MichiBackend.listaOrdenesRequest();
            return ((MichiSistemaWeb.MichiBackend.OrdenWS)(this)).listaOrdenesAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://michisistemaws.com/", ConfigurationName="MichiBackend.ProductoWS")]
    public interface ProductoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/ProductoWS/listarProductosRequest", ReplyAction="http://michisistemaws.com/ProductoWS/listarProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MichiSistemaWeb.MichiBackend.listarProductosResponse listarProductos(MichiSistemaWeb.MichiBackend.listarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/ProductoWS/listarProductosRequest", ReplyAction="http://michisistemaws.com/ProductoWS/listarProductosResponse")]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarProductosResponse> listarProductosAsync(MichiSistemaWeb.MichiBackend.listarProductosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductos", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listarProductosRequest {
        
        public listarProductosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosResponse", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://michisistemaws.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MichiSistemaWeb.MichiBackend.producto[] @return;
        
        public listarProductosResponse() {
        }
        
        public listarProductosResponse(MichiSistemaWeb.MichiBackend.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoWSChannel : MichiSistemaWeb.MichiBackend.ProductoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoWSClient : System.ServiceModel.ClientBase<MichiSistemaWeb.MichiBackend.ProductoWS>, MichiSistemaWeb.MichiBackend.ProductoWS {
        
        public ProductoWSClient() {
        }
        
        public ProductoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MichiSistemaWeb.MichiBackend.listarProductosResponse MichiSistemaWeb.MichiBackend.ProductoWS.listarProductos(MichiSistemaWeb.MichiBackend.listarProductosRequest request) {
            return base.Channel.listarProductos(request);
        }
        
        public MichiSistemaWeb.MichiBackend.producto[] listarProductos() {
            MichiSistemaWeb.MichiBackend.listarProductosRequest inValue = new MichiSistemaWeb.MichiBackend.listarProductosRequest();
            MichiSistemaWeb.MichiBackend.listarProductosResponse retVal = ((MichiSistemaWeb.MichiBackend.ProductoWS)(this)).listarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarProductosResponse> MichiSistemaWeb.MichiBackend.ProductoWS.listarProductosAsync(MichiSistemaWeb.MichiBackend.listarProductosRequest request) {
            return base.Channel.listarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarProductosResponse> listarProductosAsync() {
            MichiSistemaWeb.MichiBackend.listarProductosRequest inValue = new MichiSistemaWeb.MichiBackend.listarProductosRequest();
            return ((MichiSistemaWeb.MichiBackend.ProductoWS)(this)).listarProductosAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://michisistemaws.com/", ConfigurationName="MichiBackend.EventoWS")]
    public interface EventoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/EventoWS/listarEventoRequest", ReplyAction="http://michisistemaws.com/EventoWS/listarEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MichiSistemaWeb.MichiBackend.listarEventoResponse listarEvento(MichiSistemaWeb.MichiBackend.listarEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/EventoWS/listarEventoRequest", ReplyAction="http://michisistemaws.com/EventoWS/listarEventoResponse")]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarEventoResponse> listarEventoAsync(MichiSistemaWeb.MichiBackend.listarEventoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEvento", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listarEventoRequest {
        
        public listarEventoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventoResponse", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listarEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://michisistemaws.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MichiSistemaWeb.MichiBackend.evento[] @return;
        
        public listarEventoResponse() {
        }
        
        public listarEventoResponse(MichiSistemaWeb.MichiBackend.evento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EventoWSChannel : MichiSistemaWeb.MichiBackend.EventoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventoWSClient : System.ServiceModel.ClientBase<MichiSistemaWeb.MichiBackend.EventoWS>, MichiSistemaWeb.MichiBackend.EventoWS {
        
        public EventoWSClient() {
        }
        
        public EventoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MichiSistemaWeb.MichiBackend.listarEventoResponse MichiSistemaWeb.MichiBackend.EventoWS.listarEvento(MichiSistemaWeb.MichiBackend.listarEventoRequest request) {
            return base.Channel.listarEvento(request);
        }
        
        public MichiSistemaWeb.MichiBackend.evento[] listarEvento() {
            MichiSistemaWeb.MichiBackend.listarEventoRequest inValue = new MichiSistemaWeb.MichiBackend.listarEventoRequest();
            MichiSistemaWeb.MichiBackend.listarEventoResponse retVal = ((MichiSistemaWeb.MichiBackend.EventoWS)(this)).listarEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarEventoResponse> MichiSistemaWeb.MichiBackend.EventoWS.listarEventoAsync(MichiSistemaWeb.MichiBackend.listarEventoRequest request) {
            return base.Channel.listarEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarEventoResponse> listarEventoAsync() {
            MichiSistemaWeb.MichiBackend.listarEventoRequest inValue = new MichiSistemaWeb.MichiBackend.listarEventoRequest();
            return ((MichiSistemaWeb.MichiBackend.EventoWS)(this)).listarEventoAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://michisistemaws.com/", ConfigurationName="MichiBackend.ClienteWS")]
    public interface ClienteWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/ClienteWS/listaClientesRequest", ReplyAction="http://michisistemaws.com/ClienteWS/listaClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MichiSistemaWeb.MichiBackend.listaClientesResponse listaClientes(MichiSistemaWeb.MichiBackend.listaClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/ClienteWS/listaClientesRequest", ReplyAction="http://michisistemaws.com/ClienteWS/listaClientesResponse")]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaClientesResponse> listaClientesAsync(MichiSistemaWeb.MichiBackend.listaClientesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaClientes", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listaClientesRequest {
        
        public listaClientesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaClientesResponse", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listaClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://michisistemaws.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MichiSistemaWeb.MichiBackend.cliente[] @return;
        
        public listaClientesResponse() {
        }
        
        public listaClientesResponse(MichiSistemaWeb.MichiBackend.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteWSChannel : MichiSistemaWeb.MichiBackend.ClienteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteWSClient : System.ServiceModel.ClientBase<MichiSistemaWeb.MichiBackend.ClienteWS>, MichiSistemaWeb.MichiBackend.ClienteWS {
        
        public ClienteWSClient() {
        }
        
        public ClienteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MichiSistemaWeb.MichiBackend.listaClientesResponse MichiSistemaWeb.MichiBackend.ClienteWS.listaClientes(MichiSistemaWeb.MichiBackend.listaClientesRequest request) {
            return base.Channel.listaClientes(request);
        }
        
        public MichiSistemaWeb.MichiBackend.cliente[] listaClientes() {
            MichiSistemaWeb.MichiBackend.listaClientesRequest inValue = new MichiSistemaWeb.MichiBackend.listaClientesRequest();
            MichiSistemaWeb.MichiBackend.listaClientesResponse retVal = ((MichiSistemaWeb.MichiBackend.ClienteWS)(this)).listaClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaClientesResponse> MichiSistemaWeb.MichiBackend.ClienteWS.listaClientesAsync(MichiSistemaWeb.MichiBackend.listaClientesRequest request) {
            return base.Channel.listaClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listaClientesResponse> listaClientesAsync() {
            MichiSistemaWeb.MichiBackend.listaClientesRequest inValue = new MichiSistemaWeb.MichiBackend.listaClientesRequest();
            return ((MichiSistemaWeb.MichiBackend.ClienteWS)(this)).listaClientesAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://michisistemaws.com/", ConfigurationName="MichiBackend.TrabajadorWS")]
    public interface TrabajadorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/TrabajadorWS/listarTrabajadoresRequest", ReplyAction="http://michisistemaws.com/TrabajadorWS/listarTrabajadoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MichiSistemaWeb.MichiBackend.listarTrabajadoresResponse listarTrabajadores(MichiSistemaWeb.MichiBackend.listarTrabajadoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://michisistemaws.com/TrabajadorWS/listarTrabajadoresRequest", ReplyAction="http://michisistemaws.com/TrabajadorWS/listarTrabajadoresResponse")]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarTrabajadoresResponse> listarTrabajadoresAsync(MichiSistemaWeb.MichiBackend.listarTrabajadoresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTrabajadores", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listarTrabajadoresRequest {
        
        public listarTrabajadoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTrabajadoresResponse", WrapperNamespace="http://michisistemaws.com/", IsWrapped=true)]
    public partial class listarTrabajadoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://michisistemaws.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MichiSistemaWeb.MichiBackend.trabajador[] @return;
        
        public listarTrabajadoresResponse() {
        }
        
        public listarTrabajadoresResponse(MichiSistemaWeb.MichiBackend.trabajador[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrabajadorWSChannel : MichiSistemaWeb.MichiBackend.TrabajadorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrabajadorWSClient : System.ServiceModel.ClientBase<MichiSistemaWeb.MichiBackend.TrabajadorWS>, MichiSistemaWeb.MichiBackend.TrabajadorWS {
        
        public TrabajadorWSClient() {
        }
        
        public TrabajadorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrabajadorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrabajadorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrabajadorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MichiSistemaWeb.MichiBackend.listarTrabajadoresResponse MichiSistemaWeb.MichiBackend.TrabajadorWS.listarTrabajadores(MichiSistemaWeb.MichiBackend.listarTrabajadoresRequest request) {
            return base.Channel.listarTrabajadores(request);
        }
        
        public MichiSistemaWeb.MichiBackend.trabajador[] listarTrabajadores() {
            MichiSistemaWeb.MichiBackend.listarTrabajadoresRequest inValue = new MichiSistemaWeb.MichiBackend.listarTrabajadoresRequest();
            MichiSistemaWeb.MichiBackend.listarTrabajadoresResponse retVal = ((MichiSistemaWeb.MichiBackend.TrabajadorWS)(this)).listarTrabajadores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarTrabajadoresResponse> MichiSistemaWeb.MichiBackend.TrabajadorWS.listarTrabajadoresAsync(MichiSistemaWeb.MichiBackend.listarTrabajadoresRequest request) {
            return base.Channel.listarTrabajadoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<MichiSistemaWeb.MichiBackend.listarTrabajadoresResponse> listarTrabajadoresAsync() {
            MichiSistemaWeb.MichiBackend.listarTrabajadoresRequest inValue = new MichiSistemaWeb.MichiBackend.listarTrabajadoresRequest();
            return ((MichiSistemaWeb.MichiBackend.TrabajadorWS)(this)).listarTrabajadoresAsync(inValue);
        }
    }
}
